let num1 = 5;
let num2 = 7;
let num3 = 9;
let promedio = (num1 + num2 + num3)/ 3;
console.log ('El promedio entre: '+ num1 + ', '+ num2 + ' y '+ num3 + ' es = ' + promedio)
//EL promedio entre 5, 7 y 9 es = 7
num1 = -3;
num2 = -2;
num3 = -8;
promedio = (num1 + num2 + num3)/ 3;
console.log ('El promedio entre: '+ num1 + ', '+ num2 + ' y '+ num3 + ' es = ' + promedio)
// El promedio entre -3, -2 y -8 = 4.3
num1 = -1.2;
num2 = 5.3;
num3 = -3.3;
promedio = (num1 + num2 + num3)/ 3;
console.log ('El promedio entre: '+ num1 + ', '+ num2 + ' y '+ num3 + ' es = ' + promedio)
// El promedio entre -1.2, 5.3 y -3.3 = 0.26